"""`printer.client` — a routed capability (BIZ-250/BIZ-251): every enabled printer plugin serves it; each printer is bound to
the provider stored on its row and core calls it with `PluginHost.call_for(PRINTER_CLIENT, plugin_id, lambda p: ...)`.

The Protocol is the typed contract a provider must satisfy (checked when its instance is built). Methods mirror
`services/abstract_printer_client.AbstractPrinterClient`, which remains the base class vendors subclass during the migration.
Printer methods are blocking (threads) — `call_for` runs them off the event loop."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .definition import CapabilityDef, RoutedCapability


@runtime_checkable
class PrinterProvider(Protocol):
    @property
    def connected(self) -> bool: ...

    @property
    def is_idle(self) -> bool: ...

    @property
    def is_printing(self) -> bool: ...

    def connect(self, loop: Any = None) -> None: ...

    def disconnect(self, timeout: int = 0) -> None: ...

    def start_print(self, file_name: str, options: Any = None) -> bool: ...

    def stop_print(self) -> bool: ...

    def pause_print(self) -> bool: ...

    def resume_print(self) -> bool: ...

    def send_gcode(self, gcode: str) -> bool: ...

    def request_status_update(self) -> None: ...

    def get_capabilities(self) -> Any: ...

    def get_alarms(self) -> list: ...

    def orca_export_args(self, file_base: str) -> list[str]: ...

    def upload_file(self, data: bytes, filename: str) -> bool: ...

    def list_files(self, directory: str = "/") -> list: ...

    def delete_file(self, file_id: str) -> bool: ...

    def download_file(self, file_id: str, max_bytes: int | None = None) -> bytes | None: ...

    def home(self) -> bool: ...

    def jog(self, axis: str, distance_mm: float) -> bool: ...

    def jog_z(self, distance_mm: float, force: bool = False) -> bool: ...

    def home_axes(self, axes: str) -> bool: ...

    def set_bed_temp(self, celsius: int) -> bool: ...

    def set_nozzle_temp(self, celsius: int) -> bool: ...

    def set_chamber_temp(self, celsius: int) -> bool: ...

    def set_fan_speeds(self, model_pct: int, aux_pct: int, box_pct: int) -> bool: ...

    def set_chamber_light(self, on: bool) -> bool: ...


DEFINITION = CapabilityDef(
    id="printer.client", version=1, label="Printer client", mode="routed", protocol=PrinterProvider,
    description="Printer control and status; every enabled provider serves it, bound per printer.")

PRINTER_CLIENT: RoutedCapability[PrinterProvider] = RoutedCapability("printer.client")
