"""Jobs on a pre-sliced .gcode upload (BIZ-188): no slicing, no overrides, estimate read from the header."""
from unittest.mock import patch

import pytest

from app.services.providers.laminus.overrides import CURATED_KEYS

KEY = sorted(CURATED_KEYS)[0]
GCODE = (
    b"; generated by OrcaSlicer\n"
    b"; filament used [g] = 12.5\n"
    b"; estimated printing time (normal mode) = 1h 2m 3s\n"
    b"G28\nG1 X10 Y10\n"
)
P1S = "Bambu Lab P1S 0.4"


@pytest.fixture
def library(tmp_path, monkeypatch):
    monkeypatch.setenv("THEMIS_LIBRARY_DIR", str(tmp_path / "library"))
    monkeypatch.setenv("THEMIS_DATA_DIR", str(tmp_path / "data"))
    return tmp_path / "library"


async def _post(client, body):
    with patch("app.api.routes.jobs.queue_engine"):
        return await client.post("/api/v1/jobs", json=body)


async def test_upload_accepts_gcode_and_reads_plate_estimate(client, library, upload_3mf):
    file_id = await upload_3mf("part.gcode", GCODE)

    plates = (await client.get(f"/api/v1/files/{file_id}/plates")).json()["plates"]

    assert [(p["plate_number"], p["estimated_time"], p["filament_g"]) for p in plates] == [(1, 3723, 12.5)]


async def test_upload_still_rejects_other_types(client, library):
    resp = await client.post("/api/v1/files/upload", files={"file": ("part.txt", b"x", "text/plain")})
    assert resp.status_code == 422


async def test_gcode_job_needs_no_print_profile_and_drops_overrides(
        client, library, upload_3mf, create_printer, session_factory):
    from app.models import Job
    file_id = await upload_3mf("part.gcode", GCODE)
    pid = await create_printer(printer_type="elegoo_centauri")

    resp = await _post(client, {
        "uploaded_file_id": file_id,
        "printer_configs": [{"printer_id": pid, "filament_type": "any", "filament_color": "any"}],
        "overrides": {KEY: "0.1"},
    })

    assert resp.status_code == 201, resp.text
    body = resp.json()
    assert body["overrides"] is None
    assert (body["estimate_status"], body["estimate_seconds"], body["estimate_filament_grams"]) == ("done", 3723, 12.5)
    async with session_factory() as s:
        assert (await s.get(Job, body["id"])).overrides is None


async def test_gcode_job_must_name_printers_or_a_model(client, library, upload_3mf):
    resp = await _post(client, {"uploaded_file_id": await upload_3mf("part.gcode", GCODE)})
    assert resp.status_code == 422


async def test_gcode_job_can_target_a_model(client, library, upload_3mf, create_printer, session_factory):
    from sqlalchemy import select
    from app.models import JobPrinterConfig
    pid = await create_printer(printer_type="elegoo_centauri", current_orca_printer_profile=P1S, orca_printer_profiles=[P1S])

    resp = await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "model_targets": [{"machine_profile": P1S, "filament_type": "any", "filament_color": "any"}],
    })

    assert resp.status_code == 201, resp.text
    async with session_factory() as s:
        rows = (await s.execute(select(JobPrinterConfig).where(JobPrinterConfig.job_id == resp.json()["id"]))).scalars().all()
    assert [r.printer_id for r in rows] == [pid]


async def test_editing_a_gcode_job_keeps_dropping_overrides(client, library, upload_3mf, create_printer):
    pid = await create_printer(printer_type="elegoo_centauri")
    job_id = (await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "printer_configs": [{"printer_id": pid, "filament_type": "any", "filament_color": "any"}],
    })).json()["id"]

    with patch("app.api.routes.jobs.queue_engine"):
        resp = await client.patch(f"/api/v1/jobs/{job_id}/configs", json={
            "printer_configs": [{"printer_id": pid, "filament_type": "any", "filament_color": "any"}], "overrides": {KEY: "0.1"}})

    assert resp.status_code == 200, resp.text
    assert resp.json()["overrides"] is None
    assert resp.json()["estimate_status"] == "done"


async def test_verify_slice_refused_for_gcode_job(client, library, upload_3mf, create_printer):
    pid = await create_printer(printer_type="elegoo_centauri")
    job_id = (await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "printer_configs": [{"printer_id": pid, "filament_type": "any", "filament_color": "any"}],
    })).json()["id"]

    resp = await client.post(f"/api/v1/jobs/{job_id}/verify-slice", json={"printer_id": pid})

    assert resp.status_code == 422


async def test_3mf_job_still_keeps_overrides(client, library, upload_3mf, create_printer):
    pid = await create_printer(printer_type="elegoo_centauri")
    resp = await _post(client, {
        "uploaded_file_id": await upload_3mf(),
        "printer_configs": [{"printer_id": pid, "print_profile": "0.20mm", "filament_type": "any", "filament_color": "any"}],
        "overrides": {KEY: "0.1"},
    })
    assert resp.status_code == 201
    assert resp.json()["overrides"] == {KEY: "0.1"}


async def test_gcode_job_refused_for_a_printer_that_cannot_take_raw_gcode(client, library, upload_3mf, create_printer):
    bambu = await create_printer()   # Bambu only ingests a sliced 3MF
    resp = await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "printer_configs": [{"printer_id": bambu, "filament_type": "any", "filament_color": "any"}],
    })
    assert resp.status_code == 422
    assert "raw .gcode" in resp.json()["detail"]


async def test_gcode_job_refused_for_a_model_only_bambu_printers_have(client, library, upload_3mf, create_printer):
    await create_printer(current_orca_printer_profile=P1S, orca_printer_profiles=[P1S])
    resp = await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "model_targets": [{"machine_profile": P1S}],
    })
    assert resp.status_code == 422


async def test_gcode_target_skips_printers_that_cannot_take_raw_gcode(
        client, library, upload_3mf, create_printer, session_factory):
    from sqlalchemy import select
    from app.models import JobPrinterConfig
    await create_printer(name="bambu", current_orca_printer_profile=P1S, orca_printer_profiles=[P1S])
    ok = await create_printer(name="centauri", printer_type="elegoo_centauri",
                              current_orca_printer_profile=P1S, orca_printer_profiles=[P1S])

    resp = await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "model_targets": [{"machine_profile": P1S}],
    })

    assert resp.status_code == 201, resp.text
    async with session_factory() as s:
        rows = (await s.execute(select(JobPrinterConfig).where(JobPrinterConfig.job_id == resp.json()["id"]))).scalars().all()
    assert [r.printer_id for r in rows] == [ok]


async def test_complete_manually_refused_for_gcode_job(client, library, upload_3mf, create_printer):
    pid = await create_printer(printer_type="elegoo_centauri")
    job_id = (await _post(client, {
        "uploaded_file_id": await upload_3mf("part.gcode", GCODE),
        "printer_configs": [{"printer_id": pid, "filament_type": "any", "filament_color": "any"}],
    })).json()["id"]
    resp = await client.post(f"/api/v1/jobs/{job_id}/complete-manually", json={"printer_id": pid})
    assert resp.status_code == 422
